# Koa Sonos StreamDeck Configuration

# Sonos speaker settings
sonos:
  speaker_name: "Koa's room"

# StreamDeck settings
streamdeck:
  brightness: 80
  http_port: 8000

# Podcast settings (global)
podcasts:
  episodes_to_download: 15  # How many latest episodes to download per podcast
  episodes_to_keep: 50  # Maximum episodes to keep per podcast (deletes oldest)

# Button configuration
# Each button can be: "loop" (repeating audio), "podcast", or "spotify" (playlist/album)
buttons:
  0:
    type: "loop"
    name: "White Noise"
    audio_file: "music/white_noise.mp3"
    icon: "icons/white_noise.png"
  
  1:
    type: "podcast"
    name: "Million Bazillion"
    rss: "https://feeds.publicradio.org/public_feeds/million-bazillion"
    icon: "icons/mb.png"
  
  2:
    type: "podcast"
    name: "Short and Curly"
    rss: "https://www.abc.net.au/feeds/7388142/podcast.xml"
    icon: "icons/sc.png"

  3:
    type: "podcast"
    name: "NPR News Now"
    rss: "https://feeds.npr.org/500005/podcast.xml"
    icon: "icons/npr.png"

  4:
    type: "spotify"
    name: "This is Taylor Swift"
    uri: "spotify:playlist:37i9dQZF1DX5KpP2LN299J"
    icon: "icons/ts.png"

  # Example buttons:
  # 5:
  #   type: "loop"
  #   name: "Rain Sounds"
  #   audio_file: "music/rain.mp3"
  #   icon: "icons/rain.png"
  #
  # 6:
  #   type: "spotify"
  #   name: "Kids Music"
  #   uri: "spotify:playlist:37i9dQZF1DX6z20IXmBjWI"
  #   icon: "icons/spotify.png"
  #
  # 7:
  #   type: "podcast"
  #   name: "Another Podcast"
  #   rss: "https://example.com/feed.xml"
  #   icon: "icons/podcast.png"
